### ISSUE TITLE
Restructure former role into collection

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/kubernetes#1]
##### SUMMARY

Restructure this repository's structure from a role into a collection (it contains the historical commits / data from https://github.com/ansible/ansible-kubernetes-modules).

##### ISSUE TYPE

- Feature Idea

**Comment by geerlingguy** [comment]
See: https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html#migrating-ansible-content-to-a-collection

**Comment by geerlingguy** [comment]
And eventually, this collection will go into https://galaxy.ansible.com/community, so it will be `community.kubernetes`.

**Comment by geerlingguy** [comment]
Using the following vars in `site.yaml` from the content_collector:

```
  vars:
    ansible_source_directory: ./ansible-2.9.4
    destination_directory: ~/Downloads/kubecollect
    collection_namespace: community
    collection_name: kubernetes
    collection_description: Kubernetes Collection for Ansible
    source_sub_directory: /clustering/k8s
```

Also ran into two issues with the content_collector:

  - https://github.com/ansible/content_collector/issues/20
  - https://github.com/ansible/content_collector/issues/21
