### ISSUE TITLE
Stop using json_query in integration test waiter.yml

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/kubernetes#23]
##### SUMMARY

Currently there's a task in the molecule integration tests (part of #22 / #10) which uses the `json_query()` filter, which is moving out of Ansible core into the `community.general` collection:

```yaml
    - name: Check that paused deployment wait worked
      assert:
        that:
          - condition.reason == "DeploymentPaused"
          - condition.status == "Unknown"
      vars:
        condition: '{{ pause_deploy.result.status.conditions | community.general.json_query("[?type==`Progressing`]") | first }}'
```

This filter depends on the jmespath library, which [might not be actively maintained anymore](https://github.com/jmespath/jmespath.py/issues/192), and it also requires the installation of the `community.general` collection just to make integration tests pass (afaict, there are no other dependencies on non-core plugins/filters/modules).

If possible, we should remove this dependency so we can drop the installation of the `community.general` collection from our CI workflow, and also drop the dependency on `jmespath` in our CI environment, especially since it seems the module and underlying library may not be in the best state, maintenance-wise.

##### ISSUE TYPE
- Feature request

##### COMPONENT NAME

CI
