### ISSUE TITLE
Support the selector option in the k8s module when applying service definitions

### ISSUE THREAD

**Issue by geekifier** [ansible-collections/kubernetes#27]
##### SUMMARY

This is a copy of the following GH issue: https://github.com/ansible/ansible/issues/67316.

The k8s module should support specifying selectors when applying resource definitions, similar to how `kubectl` supports it.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
k8s module

##### ADDITIONAL INFORMATION

Some commonly used projects, such as Knative, require you to apply the Custom Resource Definitions (CRDs) to the K8s cluster, before you can deploy the rest of the service definition.

See: https://knative.dev/v0.11-docs/install/knative-with-any-k8s/#installing-knative.

Without the support for specifying selectors, this is not possible in Ansible without having to use a 3rd party binary (`kubectl`). 

```yaml

# example 
- name: Install Knative CRDs                                                                                                                                                                                      
  k8s:                                   
    state: present
    src: "{{ item.dest }}"
    context: "{{ k8s_cluster | mandatory }}" 
    # this does not work
   selector:
     - 'knative.dev/crd-install=true'    
    validate:
      fail_on_error: yes                                                                                                                                                                                   
  with_items:
    - "{{ knative_install_files.results }}"

# output

msg: 'Unsupported parameters for (k8s) module: selector Supported parameters include: api_key, api_version, append_hash, apply, ca_cert, client_cert, client_key, context, force, host, kind, kubeconfig, merge_type, name, namespace, password, proxy, resource_definition, src, state, username, validate, validate_certs, wait, wait_condition, wait_sleep, wait_timeout'
```

Sample `kubectl` command utilizing selectors:

```bash
kubectl apply --selector knative.dev/crd-install=true \
--filename https://github.com/knative/serving/releases/download/v0.11.0/serving.yaml \
--filename https://github.com/knative/eventing/releases/download/v0.11.0/release.yaml \
--filename https://github.com/knative/serving/releases/download/v0.11.0/monitoring.yaml
```
