### ISSUE TITLE
k8s_module fails on subsequent runs for unpatchable resources

### ISSUE THREAD

**Issue by Gabology** [ansible-collections/kubernetes#67]
Cross posted from https://github.com/ansible/ansible/issues/68547. Not sure if this issue tracker should be used instead for k8s module issues.

##### SUMMARY
Module attempts to patch K8s Jobs (and possibly other k8s resources) which is not supported causing a fatal error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_module

##### ANSIBLE VERSION

```paste below
anansible 2.9.6
  config file = None
  configured module search path = ['/Users/foo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:28:52) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### STEPS TO REPRODUCE
Create a K8s Job using the Ansible k8s module. Execute the task once, then run it again.

##### EXPECTED RESULTS
Playbook execution should be successful on subsequent invocations regardless of if the Job is already present or not.

##### ACTUAL RESULTS

Following error is returned from K8s

```paste below
FAILED! => {"changed": false, "error": 422, "msg": "Failed to patch object: ...", "reason": "Unprocessable Entity", "status": 422}
```

**Comment by geerlingguy** [comment]
Testing the creation of a job with `kubectl`, I get:

```
$ kubectl apply -f https://kubernetes.io/examples/controllers/job.yaml
job.batch/pi created

$ kubectl apply -f https://kubernetes.io/examples/controllers/job.yaml
job.batch/pi unchanged

$ echo $?
0
```

Testing the same job definition with the following Ansible playbook:

```yaml
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - k8s:
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: pi
            namespace: default
          spec:
            template:
              spec:
                containers:
                - name: pi
                  image: perl
                  command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
                restartPolicy: Never
            backoffLimit: 4
```

I get:

```
$ ANSIBLE_PYTHON_INTERPRETER=python3 ansible-playbook test.yml

PLAY [localhost] *******************************************************************************************************

TASK [k8s] *************************************************************************************************************
changed: [127.0.0.1]

PLAY RECAP *************************************************************************************************************
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

$ ANSIBLE_PYTHON_INTERPRETER=python3 ansible-playbook test.yml

PLAY [localhost] *******************************************************************************************************

TASK [k8s] *************************************************************************************************************
ok: [127.0.0.1]

PLAY RECAP *************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

So it seems to be working for me. Can you provide any more details, like the job template that's being run/patched, which is not working for you?
