### ISSUE TITLE
k8s_log fails to read job logs

### ISSUE THREAD

**Issue by Gabology** [ansible-collections/kubernetes#68]
##### SUMMARY
k8s_log module fails to read logs for k8s jobs

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/1041791/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.2 (default, Mar 11 2020, 00:28:52) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - community.kubernetes

  tasks:
  - community.kubernetes.k8s:
      state: present
      wait: yes
      wait_timeout: 120
      wait_condition:
        type: Complete
        status: 'True'
      definition:
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: pi
          namespace: test
        spec:
          template:
            spec:
              containers:
              - name: pi
                image: perl
                command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
              restartPolicy: Never
          backoffLimit: 4

  - community.kubernetes.k8s_log:
      api_version: batch/v1
      kind: Job
      namespace: test
      name: pi
```

##### EXPECTED RESULTS
It should read logs for the pi job

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'float' object is not subscriptable
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/gabology/.ansible/tmp/ansible-tmp-1585628952.305501-193777297450161/AnsiballZ_k8s_log.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/gabology/.ansible/tmp/ansible-tmp-1585628952.305501-193777297450161/AnsiballZ_k8s_log.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/gabology/.ansible/tmp/ansible-tmp-1585628952.305501-193777297450161/AnsiballZ_k8s_log.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.kubernetes.plugins.modules.k8s_log', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/n9/q00g1dkd0p17ct_99j_0ybjrn6w01w/T/ansible_community.kubernetes.k8s_log_payload_fa6l6osp/ansible_community.kubernetes.k8s_log_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s_log.py\", line 236, in <module>\n  File \"/var/folders/n9/q00g1dkd0p17ct_99j_0ybjrn6w01w/T/ansible_community.kubernetes.k8s_log_payload_fa6l6osp/ansible_community.kubernetes.k8s_log_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s_log.py\", line 232, in main\n  File \"/var/folders/n9/q00g1dkd0p17ct_99j_0ybjrn6w01w/T/ansible_community.kubernetes.k8s_log_payload_fa6l6osp/ansible_community.kubernetes.k8s_log_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s_log.py\", line 185, in execute_module\n  File \"/usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/openshift/dynamic/client.py\", line 94, in get\n    return self.request('get', path, **kwargs)\n  File \"/usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/openshift/dynamic/client.py\", line 49, in inner\n    return serializer(self, json.loads(resp.data.decode('utf8')))\n  File \"/usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/openshift/dynamic/resource.py\", line 276, in __init__\n    kind = instance['kind']\nTypeError: 'float' object is not subscriptable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
