### ISSUE TITLE
Add k8s_status module to collection

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/kubernetes#9]
##### SUMMARY

A k8s_status module would be nice to have in certain circumstances. If you want to be able to set a status for a given resource, this module could help you do that.

See: https://github.com/operator-framework/operator-metering/blob/master/images/metering-ansible-operator/roles/meteringconfig/library/k8s_status.py

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

Example task:

```yaml
- name: Set custom status fields on TestCR
  k8s_status:
    api_version: apps.example.com/v1alpha1
    kind: TestCR
    name: my-test
    namespace: testing
    status:
        hello: world
        custom: entries
```
